- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  tags:
    install_epel

- name: Install NGINX
  yum:
    name: nginx
    disable_gpg_check: yes
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
  tags:
    install_nginx

- name: Start NGINX
  service:
    name: nginx
    state: started
  tags:
    start_nginx
